config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index"
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  get 'public_recipes', to: 'recipes#public_recipes' 
  resources :recipes, except: %i[edit update, :update] do
    resources :recipe_foods, except: %i[edit update]
    collection do
     
    end
    member do
      get 'general_shopping_list'
    end
  end
  resources :recipe_foods, only: [:new, :create, :destroy] do
    patch :modify, on: :member
  end
  resources :users, only: [:index, :show, :new, :create, :destroy]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user
    can :read, :all
    can :manage, Food, user_id: user.id
    can :manage, Recipe, user_id: user.id
    can :manage, RecipeFood, recipe: { user_id: user.id }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, class_name: 'RecipeFood'
  has_and_belongs_to_many :recipes, join_table: 'recipe_foods'

  validates :name, :measurement_unit, :price, :quantity, presence: true
  validates :quantity, numericality: { only_integer: true }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, dependent: :destroy, class_name: 'RecipeFood'
  has_and_belongs_to_many :foods, join_table: 'recipe_foods'

  validates :is_public, inclusion: { in: [true, false] }
  validates :name, :preparation_time_minutes, :cooking_time_minutes, presence: true
  validates :preparation_time_minutes, :cooking_time_minutes, numericality: { only_integer: true }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'

  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :recipe_foods, through: :recipes

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?
  # rescue_from CanCan::AccessDenied do |exception|
  #   redirect_to root_path, alert: "Access Denied: #{exception.message}"
  # end

  def after_sign_in_path_for(_resource)
    users_url
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, keys: %i[name email password confirm_password]
    )
    devise_parameter_sanitizer.permit(
      :sign_in, keys: %i[email password]
    )
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @user = current_user
    @foods = @user.foods.all
  end

  def show; end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      flash[:success] = 'Food was successfully added.'
      redirect_to foods_path, notice: 'Food was successfully added.'
    else
      flash[:error] = 'Food does not exist in your food list, please add it to your food list.'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      flash[:notice] = 'Food was successfully deleted.'
    else
      flash[:alert] = 'Failed to delete food.'
    end
    redirect_to foods_path, notice: 'Food was successfully deleted.'
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :quantity, :price, :user_id)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  # load_and_authorize_resource
  #  before_action :set_recipe

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
  end

  def show
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.build(recipe_food_params)

    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'Ingredient was successfully added.'
    else
      render :new
    end
  end

  def modify
    recipe_food = RecipeFood.find(params[:id])
    new_quantity = params[:recipe_food][:quantity]

    if recipe_food.update(quantity: new_quantity)
      flash[:success] = 'Quantity updated successfully'
    else
      flash[:error] = 'Failed to update quantity'
    end

    redirect_to recipe_food_path(recipe_food)
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_path(@recipe), notice: 'Ingredient was successfully removed.'
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:is_public_recipes]
  def public_recipes
    @public_recipes = Recipe.where(is_public: true).includes(recipe_foods: :food)
  end

  def index
    @recipes = Recipe.includes(:user).where(user_id: current_user.id)
  end

  def show
    @user = current_user
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id)
  end

  def new
    @recipe = Recipe.new
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(is_public: !@recipe.is_public)
      redirect_to @recipe, notice: 'Recipe public status was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  def create
    @user = current_user
    @recipe = @user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to recipe_path(@recipe), notice: 'The recipes Was created succesfully'
    else
      render :new
    end
  end

  def general_shopping_list
    @user = current_user
    @recipe = Recipe.includes(:recipe_foods).find_by(id: params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id)
    @needed_items = []
    @recipe_foods.each do |recipe_food|
      existed_food = @user.foods.find_by(name: recipe_food.food.name)
      if existed_food.nil?
        @needed_items << [recipe_food.food.name, recipe_food.quantity, recipe_food.food.price,
                          recipe_food.food.measurement_unit]
      else
        difference_quantity = recipe_food.quantity - existed_food.quantity
        if difference_quantity.positive?
          @needed_items << [recipe_food.food.name, difference_quantity, existed_food.price,
                            existed_food.measurement_unit]
        end
      end
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time_minutes, :cooking_time_minutes, :description, :is_public)
  end

  def calculate_total_price(recipe)
    total_price = 0.0

    recipe.recipe_foods.each do |recipe_food|
      total_price += recipe_food.food.price * recipe_food.quantity
    end

    total_price
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<div class="container p-3">
  
 <h1 class="food_title text-center h1">Foods page</h3>
 <div class="container d-flex justify-content-end pe-5">
 <%= link_to "Add Food", new_food_path, method: :post, class: "btn btn-outline-success" %>
 </div>
 <table class="table table-striped">
 <% if @foods.present? %>
     <thead>
       <tr>
         <th class="input title" >Food</th>
         <th class="input title" >Measurement unit</th>
         <th class="input title">Unit price</th>
         <th class="input title">Actions</th>
        </tr>
     </thead>
   <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td class="input"><%= food.name %></td>
        <td class="input"><%= food.measurement_unit %></td>
        <td class="input"><%= food.price %></td>
        <td class="input">
            <%= link_to 'Delete', food_path(food), data: { turbo_method: :delete, confirm: 'Are you sure?' } %>
        </td>
      </tr>
       <% end %>
       </tbody>
       <% else %> 
        <p class="text-center display-6 ">No foods found</p>
    <% end %>
</table>
</div>

app/views/foods/new.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center">
<h4> Add new food</h4>

<%= form_with model: @food, url: foods_path do |form| %>
<% if @food.errors.any? %>
 <div>
                <h2><%= pluralize(food.errors.count, "error") %> Food cannot be saved:</h2>

                <ul>
                    <% food.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <div class="d-flex flex-column w-100">

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'w-100', required: true%>
  </div>
  <div>
        <%= form.label :measurement_unit, style: "display: block" %>
        <%= form.select :measurement_unit, options_for_select(['units', 'grams', 'kg', 'pounds']), { prompt: 'Select a category  ...' }, class: 'w-100' %>
  </div>
  <div>
  <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price, class: 'w-100', required: true%>
  </div>
  <div>
   <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity, class: 'w-100', required: true%>
  </div>
   <%=form.submit "Create food", class: "btn btn-outline-dark btn-sm mt-2 float-start"%>
  </div>
  </div>
 <%end%>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary ps-4">
  <div class="container">
    <ul class="navbar-nav d-flex display-6">
      <% if user_signed_in? %>
       
        <li class="nav-item pe-5">
          <%= link_to "Foods", foods_path, class: 'nav-link' %>
        </li>
        <li class="nav-item pe-5">
          <%= link_to "Public Recipes", public_recipes_path(current_user), class: 'nav-link' %>
        </li>
        <li class="nav-item pe-5">
          <%= link_to "Recipes", recipes_path(current_user), class: 'nav-link' %>
        </li>
        <li class="nav-item pe-5">
          <%= link_to "Create Recipe", new_recipe_path(current_user), class: 'nav-link' %>
        </li>
        <li class="nav-item pe-5">
           <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link btn btn-primary' %>
        </li>
        <%# <li class="nav-item pe-5">
          <%= link_to "Shopping List", shopping_lists_path(current_user), class: 'nav-link' %>
        <%# </li> %> 
      <% else %>
       
        <li class="nav-item pe-5">
          <%= link_to "Home", public_recipes_path, class: 'nav-link' %>
        </li>
        <li class="nav-item pe-5">
          <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item pe-5">
          <%= link_to "Log In", new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <div class="navbar-text display-6">
      <% if current_user.present? %>
        <strong>User Name:</strong>
        <%= current_user.name %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">



    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%=render 'layouts/navbar'%>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <!-- Latest compiled and minified JavaScript -->
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
  </body>
</html>

app/views/recipe_foods/new.html.erb
<div class="container my-4">
  <div class="card p-4">
    <%= form_with(model: [@recipe, @recipe_food], url: recipe_recipe_foods_path(@recipe), method: :post) do |form| %>
      <div class="form-row">
        <div class="form-group col-md-6 mb-3"> <!-- Added mb-3 class for margin-bottom -->
          <%= form.label :food_id, "Food" %>
          <%= form.collection_select :food_id, current_user.foods, :id, :name, { prompt: "Select a food" }, class: "form-control" %>
        </div>

        <div class="form-group col-md-6">
          <%= form.label :quantity %>
          <%= form.number_field :quantity, class: "form-control" %>
        </div>
      </div>

      <div class="form-group mt-3">
        <%= form.submit "Create Ingredient", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipe_foods/show.html.erb
<div>
Are you sure
  <%= form_with model: @recipe_food, url: recipe_recipe_food_path(@recipe, @recipe_food), method: :delete, remote: true do |form| %>
    <%= form.submit 'Delete', class: 'delete-button' %>
  <% end %>
  <%= link_to "No", recipe_path(@recipe) %>
</div>

app/views/recipes/general_shopping_list.html.erb
<div class="container p-5 border d-flex flex-column justify-content-center align-items-center">
<h1 class="h1">Shopping list</h1>
<div class="amount d-flex justify-content-between mt-5">
  <p class="h5 p-5">Amount of food to buy: <%= @needed_items.length %></p>
  <p class="h5 p-5"> Total value of food needed: <%= @needed_items.inject(0) { |sum, item| sum + (item[1] * item[2]) } %></p>
</div>

<table class="table">
  <thead>
    <tr class="p-5">
      <th>Food</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
  </thead>
  <% @needed_items.each do |needed_item| %>
    <tbody>
      <tr>
        <td><%= needed_item[0] %></td>
        <td><%= needed_item[1]  %><%= needed_item[3] %></td>
        <td><%= needed_item[1] * needed_item[2] %></td>
      </tr>
    </tbody>
  <% end %>
</table>
</div>

app/views/recipes/index.html.erb
<div class="container mt-3">
<h1 class="h1">Recipes</h1>
  <div class="mb-4 p-2 d-flex justify-content-sm-end">
    <%= link_to "Add New Recipe", new_recipe_path, class: "btn btn-primary" %>
  </div>
  <% @recipes.each do |recipe| %>
    <div class="card mb-4">
      <div class="card-body">
        <h2 class="card-title"><%= link_to recipe.name, recipe, class: "text-decoration-none text-reset" %></h2>
        <p class="card-text"><strong>Description:</strong> <%= recipe.description %></p>
        <p class="card-text"><strong>Preparation Time:</strong> <%= recipe.preparation_time_minutes%> minutes</p>
        <p class="card-text"><strong>Cooking Time:</strong> <%= recipe.cooking_time_minutes %> minutes</p>
        
        <% if current_user == recipe.user %>
          <%= button_to "REMOVE", recipe_path(recipe.id), method: :delete, class: "btn btn-danger btn-sm" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="container d-flex justify-content-center p-5" style="height:500px">
<%= form_with(model: @recipe, class: "form") do |form| %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control", style: "width: 300px;" %>
    </div>

    <div class="form-group">
      <%= form.label :preparation_time_minutes %>
      <%= form.text_field :preparation_time_minutes, class: "form-control", style: "width: 100px;" %>
    </div>

    <div class="form-group">
      <%= form.label :cooking_time_minutes %>
      <%= form.text_field :cooking_time_minutes, class: "form-control", style: "width: 100px;" %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control", style: "width: 300px;" %>
    </div>

    <div class="form-group">
      <%= form.select :is_public, options_for_select(['true','false']), prompt: 'Public or private?' %>
    </div>

    <div class="form-group">
      <%= form.submit "Create Recipe", class: "btn btn-primary mt-3" %>
    </div>

    <%= link_to "Back to recipes", recipes_path, class: "btn btn-secondary mt-3" %>
  <% end %>
</div>

app/views/recipes/public_recipes.html.erb
<h1 class="h-1 text-center">Public Recipes</h1>
<div class="container">
  <% @public_recipes.each do |recipe| %>
    <div class="card mb-4 d-flex flex-row">
      <div class="d-flex flex-column m-5 col-3">
        <h2 class="card-title"><%= link_to recipe.name, recipe %></h2>
        <p>By: <%= recipe.user.name %></p>
      </div>
      <div class="d-flex flex-column m-5 col-9">
        <h2 class="card-title">Total food items: <%= recipe.recipe_foods.length %></h2>
        <p class="card-text">Total price:
          <%= recipe.recipe_foods.sum { |recipe_food| recipe_food.food.price * recipe_food.quantity} %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container recipe-details">
  <h2><%= @recipe.name %></h2>

  <div class="row recipe-details-box1">
    <div class="col-md-6">
      <p><strong>Preparation Time:</strong> <%= @recipe.preparation_time_minutes %> minutes</p>
    </div>

    <div class="col-md-6 text-right">
      <%= form_for @recipe, url: recipe_path(@recipe), method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :is_public, class: 'mr-4' %>
          <%= f.check_box :is_public, id: 'recipe_public', class: 'form-check-input' %>
          <%= f.submit 'Toggle', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>

  <p><strong>Cooking Time:</strong> <%= @recipe.cooking_time_minutes %> minutes</p>
  <p><strong>Description:</strong> <%= @recipe.description %></p>

  <div class="recipe-details-btns mt-3">
    <%= link_to  "Generate shopping list", general_shopping_list_recipe_path(@recipe), method: :post, class: "btn btn-success" %>
    <%= link_to "Add Ingredient", new_recipe_recipe_food_path(recipe_id: @recipe.id), class: 'btn btn-primary' %>
  </div>

  <table class="table mt-4">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe_foods.each do |recipe_food| %>
        <tr>
          <td><%= recipe_food.food.name %></td>
          <td><%= recipe_food.quantity %></td>
          <td><%= recipe_food.food.price %></td>
          <td class="action">
          <% if can? :edit, @recipe_food %>
            <%= link_to "Delete", recipe_recipe_food_path(@recipe, recipe_food), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

             <%= form_for recipe_food, url: modify_recipe_food_path(recipe_food), method: :patch, remote: true, authenticity_token: true do |f| %>
              <div class="quantity-container">
                <%= f.number_field :quantity, value: recipe_food.quantity, class: "quantity-input" %>
             
              <%= f.submit 'Modify', class: 'modify-button' %>
              </div>
            <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<div>
<h1>List of Users</h1>
<ul>
  <% @users.each do |user| %>
    <li>
      <strong>Name:</strong> <%= user.name %><br>
      <strong>Email:</strong> <%= user.email %>
    </li>
  <% end %>
</ul>
</div>